# application.yml
server:
  port: ${PORT:3001}
  servlet:
    context-path: /
  error:
    # Configurações de segurança para produção
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: mercadoclone-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    com.mercadoclone: INFO
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  data:
    products-file: classpath:data/products.json
  images:
    base-url: ${IMAGES_BASE_URL:https://raw.githubusercontent.com/wgcostta/meli-prototype/refs/heads/main/img}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

