# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 3001

logging:
  level:
    com.mercadoclone: DEBUG
    org.springframework.web: DEBUG

app:
  data:
    products-file: classpath:data/products.json
#  images:
#    base-url: http://localhost:3001/images/products