# Usar a imagem oficial do Node.js como base
FROM node:18-alpine

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos de configuração e dependências
COPY package.json package-lock.json* ./

# Instalar as dependências
RUN npm ci --production

# Copiar o restante dos arquivos do projeto
COPY . .

# Construir o projeto Next.js
RUN npm run build

# Expor a porta que o Next.js usa (padrão 3000)
EXPOSE 3000

# Comando para iniciar o aplicativo
CMD ["npm", "start"]